name: build-cycle
description: "BMAD Method Build Cycle skill - comprehensive guide for sprint planning, story creation, implementation, code review, and retrospective workflow"
author: "BMad Community"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated
implementation_artifacts: "{config_source}:implementation_artifacts"
planning_artifacts: "{config_source}:planning_artifacts"
output_folder: "{implementation_artifacts}"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/build-cycle"
instructions: "{installed_path}/instructions.md"

# Variables and inputs
variables:
  # Project context
  project_context: "**/project-context.md"
  project_name: "{config_source}:project_name"
  
  # Related workflows (for reference)
  sprint_planning_workflow: "{project-root}/_bmad/bmm/workflows/4-implementation/sprint-planning"
  create_story_workflow: "{project-root}/_bmad/bmm/workflows/4-implementation/create-story"
  dev_story_workflow: "{project-root}/_bmad/bmm/workflows/4-implementation/dev-story"
  code_review_workflow: "{project-root}/_bmad/bmm/workflows/4-implementation/code-review"
  retrospective_workflow: "{project-root}/_bmad/bmm/workflows/4-implementation/retrospective"
  correct_course_workflow: "{project-root}/_bmad/bmm/workflows/4-implementation/correct-course"
  sprint_status_workflow: "{project-root}/_bmad/bmm/workflows/4-implementation/sprint-status"
  
  # Status tracking
  status_file: "{implementation_artifacts}/sprint-status.yaml"
  epics_location: "{planning_artifacts}"

# Input file patterns
input_file_patterns:
  sprint_status:
    description: "Sprint tracking file"
    whole: "{implementation_artifacts}/sprint-status.yaml"
    load_strategy: "CHECK_EXISTS"
  epics:
    description: "All epics with user stories"
    whole: "{planning_artifacts}/*epic*.md"
    sharded: "{planning_artifacts}/*epic*/*.md"
    load_strategy: "CHECK_EXISTS"

standalone: true
